#Requires -Version 5.1
<#
.SYNOPSIS
  Start Syro RAG assistant (backend + frontend) with one command.
.DESCRIPTION
  Kills any existing process on port 8000, starts Qdrant + Redis via Docker,
  initializes the DB if needed, launches uvicorn and the Vite dev server,
  then opens the browser.
.EXAMPLE
  .\start-syro.ps1
  .\start-syro.ps1 -SkipDocker     # skip Qdrant/Redis (if already running)
  .\start-syro.ps1 -NoBrowser      # don't auto-open the browser
#>
param(
  [switch]$SkipDocker,
  [switch]$NoBrowser
)

Set-StrictMode -Off
$ErrorActionPreference = 'Stop'

$ROOT = $PSScriptRoot
$FRONTEND = Join-Path $ROOT "frontend"
$BACKEND_PORT = 8000
$FRONTEND_PORT = 5173

function Write-Step { param($msg) Write-Host "  >> $msg" -ForegroundColor Cyan }
function Write-Ok   { param($msg) Write-Host "  OK $msg" -ForegroundColor Green }
function Write-Warn { param($msg) Write-Host "  !! $msg" -ForegroundColor Yellow }
function Write-Fail { param($msg) Write-Host "  XX $msg" -ForegroundColor Red }

Write-Host ""
Write-Host "  * SYRO - Starting up" -ForegroundColor Magenta
Write-Host ""

# 1. Check prerequisites
Write-Step "Checking prerequisites..."

$missing = @()
if (-not (Get-Command python  -ErrorAction SilentlyContinue)) { $missing += "python" }
if (-not (Get-Command uvicorn -ErrorAction SilentlyContinue)) { $missing += "uvicorn (pip install uvicorn)" }
if (-not (Get-Command npm     -ErrorAction SilentlyContinue)) { $missing += "npm / Node.js" }

if ($missing.Count -gt 0) {
  Write-Fail "Missing: $($missing -join ', ')"
  exit 1
}
Write-Ok "python, uvicorn, npm found"

# 2. Generate .env if missing
$envFile = Join-Path $ROOT ".env"
if (-not (Test-Path $envFile)) {
  Write-Step "Generating .env..."
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  $bytes = New-Object byte[] 32
  $rng.GetBytes($bytes)
  $secret = [System.Convert]::ToBase64String($bytes)

  $envContent = @"
# Auto-generated by start-syro.ps1
SECRET_KEY=$secret
DEBUG=true
LOG_LEVEL=INFO

# LLM
LLM_PROVIDER=ollama
OLLAMA_BASE_URL=http://localhost:11434/v1
CHAT_MODEL=llama3.2
EMBEDDINGS_MODEL=nomic-embed-text
EMBEDDING_DIMENSIONS=768

# Storage
DB_PATH=db/syro.db
QDRANT_URL=http://localhost:6333

# Async tasks
CELERY_BROKER_URL=redis://localhost:6379/0
CELERY_RESULT_BACKEND=redis://localhost:6379/0
CELERY_TASK_ALWAYS_EAGER=false

# CORS
CORS_ALLOW_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
"@
  [System.IO.File]::WriteAllText($envFile, $envContent, [System.Text.Encoding]::UTF8)
  Write-Ok ".env created"
} else {
  Write-Ok ".env already exists"
}

# 3. Kill existing process on port 8000
Write-Step "Freeing port $BACKEND_PORT..."
$netstatLines = cmd /c "netstat -ano" 2>$null | Where-Object { $_ -match ":$BACKEND_PORT\s" -and $_ -match "LISTENING" }
if ($netstatLines) {
  $line = ($netstatLines | Select-Object -First 1).Trim()
  $parts = ($line -split '\s+') | Where-Object { $_ -ne '' }
  $pidVal = $parts | Select-Object -Last 1
  try {
    cmd /c "taskkill /PID $pidVal /F" 2>$null | Out-Null
    Start-Sleep -Milliseconds 600
    Write-Ok "Killed PID $pidVal on port $BACKEND_PORT"
  } catch {
    Write-Warn "Could not kill PID $pidVal - port may still be in use"
  }
} else {
  Write-Ok "Port $BACKEND_PORT is free"
}

# 4. Start Docker services (Qdrant + Redis)
if (-not $SkipDocker) {
  $dockerCmd = Get-Command docker -ErrorAction SilentlyContinue
  if ($dockerCmd) {
    Write-Step "Starting Qdrant + Redis via Docker..."
    $compose = Join-Path $ROOT "infra\docker-compose.dev-local.yml"
    $ErrorActionPreference = 'Continue'
    docker compose -f $compose up -d 2>&1 | Out-Null
    $ErrorActionPreference = 'Stop'

    Write-Step "Waiting for Qdrant (port 6333)..."
    $qdrantReady = $false
    for ($i = 0; $i -lt 20; $i++) {
      try {
        $r = Invoke-WebRequest -Uri "http://localhost:6333/" -TimeoutSec 2 -UseBasicParsing -ErrorAction SilentlyContinue
        if ($r.StatusCode -eq 200) { $qdrantReady = $true; break }
      } catch { }
      Start-Sleep -Seconds 1
    }
    if ($qdrantReady) { Write-Ok "Qdrant ready" } else { Write-Warn "Qdrant not responding - RAG search may fail" }
  } else {
    Write-Warn "Docker not found - skipping Qdrant/Redis"
  }
} else {
  Write-Ok "Docker skipped (-SkipDocker)"
}

# 5. Init DB if needed
$dbPath = Join-Path $ROOT "db\syro.db"
if (-not (Test-Path $dbPath)) {
  Write-Step "Initializing database..."
  Push-Location $ROOT
  try {
    $initOut = python scripts/init_db.py 2>&1
    Write-Ok "Database initialized"
    $credLines = $initOut | Select-String -Pattern "email|password|owner" -CaseSensitive:$false
    if ($credLines) {
      Write-Host ""
      Write-Host "  --- Default credentials ---" -ForegroundColor DarkGray
      $credLines | ForEach-Object { Write-Host "  $_" -ForegroundColor DarkCyan }
      Write-Host "  ---------------------------" -ForegroundColor DarkGray
      Write-Host ""
    }
  } catch {
    Write-Warn "DB init failed: $_"
  }
  Pop-Location
} else {
  Write-Ok "Database exists"
}

# 6. Start backend
Write-Step "Starting FastAPI backend (port $BACKEND_PORT)..."
$backendJob = Start-Job -ScriptBlock {
  param($root, $port)
  Set-Location $root
  uvicorn app.main:app --host 127.0.0.1 --port $port 2>&1
} -ArgumentList $ROOT, $BACKEND_PORT

Write-Step "Waiting for backend..."
$backendReady = $false
for ($i = 0; $i -lt 30; $i++) {
  try {
    $r = Invoke-WebRequest -Uri "http://127.0.0.1:$BACKEND_PORT/health" -TimeoutSec 2 -UseBasicParsing -ErrorAction SilentlyContinue
    if ($r.StatusCode -eq 200) { $backendReady = $true; break }
  } catch { }
  Start-Sleep -Seconds 1
}

if ($backendReady) {
  Write-Ok "Backend ready at http://127.0.0.1:$BACKEND_PORT"
} else {
  Write-Fail "Backend did not start in 30s"
  Receive-Job $backendJob -ErrorAction SilentlyContinue | Select-Object -Last 10 | ForEach-Object { Write-Host "  [api] $_" -ForegroundColor DarkRed }
  Write-Warn "Continuing - frontend will show retry UI"
}

# 7. Start frontend
Write-Step "Starting Vite frontend (port $FRONTEND_PORT)..."
$frontendJob = Start-Job -ScriptBlock {
  param($dir)
  Set-Location $dir
  npm run dev 2>&1
} -ArgumentList $FRONTEND

Write-Step "Waiting for frontend..."
$frontendReady = $false
for ($i = 0; $i -lt 20; $i++) {
  try {
    $r = Invoke-WebRequest -Uri "http://localhost:$FRONTEND_PORT" -TimeoutSec 2 -UseBasicParsing -ErrorAction SilentlyContinue
    if ($r.StatusCode -eq 200) { $frontendReady = $true; break }
  } catch { }
  Start-Sleep -Seconds 1
}

if ($frontendReady) { Write-Ok "Frontend ready at http://localhost:$FRONTEND_PORT" } else { Write-Warn "Frontend still starting..." }

# 8. Open browser
if (-not $NoBrowser) {
  Start-Sleep -Milliseconds 500
  Start-Process "http://localhost:$FRONTEND_PORT"
}

# Summary
Write-Host ""
Write-Host "  +-----------------------------------------------+" -ForegroundColor DarkGray
Write-Host "  |  SYRO is running                              |" -ForegroundColor Magenta
Write-Host "  |                                               |" -ForegroundColor DarkGray
Write-Host "  |  Frontend  ->  http://localhost:$FRONTEND_PORT         |" -ForegroundColor Cyan
Write-Host "  |  Backend   ->  http://127.0.0.1:$BACKEND_PORT          |" -ForegroundColor Cyan
Write-Host "  |  API docs  ->  http://127.0.0.1:$BACKEND_PORT/docs     |" -ForegroundColor Cyan
Write-Host "  |                                               |" -ForegroundColor DarkGray
Write-Host "  |  Press Ctrl+C to stop all services            |" -ForegroundColor DarkGray
Write-Host "  +-----------------------------------------------+" -ForegroundColor DarkGray
Write-Host ""

# Keep alive + stream logs
try {
  Write-Host "  Streaming backend logs (Ctrl+C to quit)..." -ForegroundColor DarkGray
  while ($true) {
    $out = Receive-Job $backendJob -ErrorAction SilentlyContinue
    if ($out) { $out | ForEach-Object { Write-Host "  [api] $_" -ForegroundColor DarkGray } }
    Start-Sleep -Seconds 2
  }
} finally {
  Write-Host ""
  Write-Step "Shutting down..."
  Stop-Job $backendJob, $frontendJob -ErrorAction SilentlyContinue
  Remove-Job $backendJob, $frontendJob -ErrorAction SilentlyContinue -Force
  Write-Ok "Done."
}
